-- MySQL Script generated by MySQL Workbench
-- Sat 23 Jul 2022 11:38:21 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema base-excell
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `base-excell` ;

-- -----------------------------------------------------
-- Schema base-excell
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base-excell` ;
USE `base-excell` ;

-- -----------------------------------------------------
-- Table `base-excell`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base-excell`.`companies` ;

CREATE TABLE IF NOT EXISTS `base-excell`.`companies` (
    `document_number` CHAR(14) NOT NULL,
    `name` VARCHAR(120) NULL,
    `created_at` DATETIME NOT NULL,
    `disabled_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`document_number`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base-excell`.`contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base-excell`.`contracts` ;

CREATE TABLE IF NOT EXISTS `base-excell`.`contracts` (
    `customer_document_number` CHAR(14) NOT NULL,
    `company_document_number` CHAR(14) NOT NULL,
    `contract_number` VARCHAR(10) NOT NULL,
    `value` DECIMAL(10,2) NOT NULL,
    `installments_size` INT(11) NOT NULL,
    `warning_level` ENUM('low', 'medium', 'high') NOT NULL,
    `reference_date` DATE NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NULL,
    `disabled_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`customer_document_number`, `company_document_number`, `contract_number`),
    CONSTRAINT `fk_contracts_customers1`
    FOREIGN KEY (`customer_document_number`)
    REFERENCES `base-excell`.`customers` (`document_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_contracts_companies1`
    FOREIGN KEY (`company_document_number`)
    REFERENCES `base-excell`.`companies` (`document_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_contracts_customers1_idx` ON `base-excell`.`contracts` (`customer_document_number` ASC) VISIBLE;

CREATE INDEX `fk_contracts_companies1_idx` ON `base-excell`.`contracts` (`company_document_number` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `base-excell`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base-excell`.`customers` ;

CREATE TABLE IF NOT EXISTS `base-excell`.`customers` (
    `document_number` CHAR(14) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `type` ENUM('pf', 'pj') NOT NULL,
    `created_at` DATETIME NOT NULL,
    `disabled_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`document_number`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base-excell`.`phones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base-excell`.`phones` ;

CREATE TABLE IF NOT EXISTS `base-excell`.`phones` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_document_number` CHAR(14) NOT NULL,
    `ddd` INT(2) NOT NULL,
    `phone` INT(9) NOT NULL,
    `is_checked` TINYINT(1) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `disabled_at` DATETIME NULL,
    `updated_at` DATETIME NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`, `customer_document_number`),
    CONSTRAINT `fk_phones_customers1`
    FOREIGN KEY (`customer_document_number`)
    REFERENCES `base-excell`.`customers` (`document_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_phones_customers1_idx` ON `base-excell`.`phones` (`customer_document_number` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
